
language: node_js
sudo: false
node_js:
  - '8'

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run test
